### ISSUE TITLE
issue with Android gradle plugin 4.*

### ISSUE THREAD

**Issue by codeCleanDev** [Lzhiyong/build-tools#4]
I got this error with Android gradle 4.0.1:
Unknown Option : aapt2 :
'--no-proguard-location-reference'
But when i changed the gradle classpath to 3.6.4
The build successfully done 
. 
Any solution for this.

**Comment by Lzhiyong** [comment]
I have recompiled all the binaries, from the latest Android 11 source code

please download the lastest sdk tools v2 version from release

> I got this error with Android gradle 4.0.1:
> Unknown Option : aapt2 :
> '--no-proguard-location-reference'
> But when i changed the gradle classpath to 3.6.4
> The build successfully done
> .
> Any solution for this.

I have recompiled all the binaries, from the latest Android 11 source code

please download the lastest sdk tools v2 version from release

**Comment by Lzhiyong** [comment]
> I got this error with Android gradle 4.0.1:
> Unknown Option : aapt2 :
> '--no-proguard-location-reference'
> But when i changed the gradle classpath to 3.6.4
> The build successfully done
> .
> Any solution for this.

I have recompiled all the binaries from the latest Android 11 source code

please download the lastest sdk tools v2 version from release

**Comment by Lzhiyong** [comment]
> I got this error with Android gradle 4.0.1:
> Unknown Option : aapt2 :
> '--no-proguard-location-reference'
> But when i changed the gradle classpath to 3.6.4
> The build successfully done
> .
> Any solution for this.

I have recompiled all the binaries files from the latest Android 11 source code

please download the lastest sdk tools v2 version from release

**Comment by codeCleanDev** [comment]
Done
